#!/usr/bin/env bash
# Run Apache on the holbertonschool/265-0 docker container
# get Apache to run on the container and to return a page containing Hello Holberton

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
